services:
  # Backend Service - Consolidated Laravel API
  backend-service:
    build: ./backend-service
    container_name: autofill-backend-service
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_DATABASE=autofill_backend
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - APP_KEY=base64:$(openssl rand -base64 32)
    volumes:
      - ./backend-service:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - autofill-network

  # Database - PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: autofill-db
    environment:
      - POSTGRES_DB=autofill_backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - autofill-network

  # Redis - Caching and sessions
  redis:
    image: redis:7-alpine
    container_name: autofill-redis
    ports:
      - "6379:6379"
    networks:
      - autofill-network
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  autofill-network:
    driver: bridge
