services:
  # Backend Service - Consolidated Laravel API
  backend-service:
    build: ./backend-service
    container_name: autofill-backend-service
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend-service/.env
    volumes:
      - ./backend-service:/var/www/html
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - autofill-network

  # Database - PostgreSQL
  db:
    build: ./db
    container_name: autofill-db
    restart: always
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./database/init:/docker-entrypoint-initdb.d # When it initializes a new, empty database, it will automatically run any .sql, .sql.gz, or .sh files found in that folder.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d autofill_backend"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - autofill-network

  # Queue Worker - Process background jobs
  queue-worker:
    build: ./backend-service
    container_name: autofill-queue-worker
    restart: always
    env_file:
      - ./backend-service/.env
    volumes:
      - ./backend-service:/var/www/html
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - autofill-network
    command: supervisord -n -c /etc/supervisor/supervisord.conf

  # Redis - Caching and sessions
  redis:
    build: ./redis
    container_name: autofill-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - autofill-network
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  autofill-network:
    driver: bridge
